version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: bookstoredb
      POSTGRES_USER: bookstoreuser
      POSTGRES_PASSWORD: bookstorepassword
